// !!!!! GENERATED BY me.roybailey.generator.code.ServiceCodeGenerator !!!!!
package me.roybailey.codegen.api.tempcities

import me.roybailey.api.common.BaseService
import me.roybailey.codegen.jooq.database.Tables.TEMP_CITIES
import me.roybailey.codegen.jooq.database.tables.records.TempCitiesRecord
import me.roybailey.codegen.jooq.database.tables.pojos.TempCities
import org.jooq.*
import org.jooq.impl.DSL.*
import org.springframework.stereotype.Component


@Component
class TempCitiesService(protected open val dsl: DSLContext) : BaseService("cities","TEMP_CITIES") {

    fun getAllData(params: Map<String,Any>): List<TempCities> {
        val results = dsl
            .select()
            .from(TEMP_CITIES)
            .where(getFilterCondition(params, TEMP_CITIES))
            .fetch()
            .into(TempCities::class.java)
        return results;
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ServiceCodeGenerator !!!!!
