// !!!!! GENERATED BY me.roybailey.generator.code.PojoCodeGenerator !!!!!
package me.roybailey.codegen.api.tempcities

import com.fasterxml.jackson.annotation.JsonProperty


data class TempCities (
    
    @JsonProperty("id") var id: Integer,
    
    @JsonProperty("population") var population: Integer,
    
    @JsonProperty("name") var name: String,
    
)

// !!!!! GENERATED BY me.roybailey.generator.code.PojoCodeGenerator !!!!!
