// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
package me.roybailey.codegen.api.tempcities

import javax.servlet.http.HttpServletRequest
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import me.roybailey.api.common.BaseController
import me.roybailey.codegen.jooq.database.tables.pojos.TempCities


@RestController
class TempCitiesController(private val tempcitiesService: TempCitiesService) : BaseController() {

    @GetMapping
    @RequestMapping("/tempcities")
    fun getAllData(request:HttpServletRequest): List<TempCities> {
        return tempcitiesService.getAllData(request.parameterMap);
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
