package me.roybailey.generator.code

import com.github.jknack.handlebars.Handlebars
import me.roybailey.api.blueprint.ApiBlueprint
import me.roybailey.api.blueprint.ApiTableMapping
import me.roybailey.generator.ConfigurationProperties
import mu.KotlinLogging
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component
import java.io.File
import java.nio.file.Files.createDirectories
import java.nio.file.Path


@Component
class ControllerCodeGenerator {

    private val logger = KotlinLogging.logger {}

    @Autowired
    lateinit var properties: ConfigurationProperties

    @Autowired
    lateinit var apiBlueprints: List<ApiBlueprint>

    val controllerTemplate = """ 
package {{PACKAGE_NAME}}

import javax.servlet.http.HttpServletRequest
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import me.roybailey.api.common.BaseController
import me.roybailey.codegen.jooq.database.tables.pojos.{{DOMAIN_NAME}}


@RestController
class {{DOMAIN_NAME}}Controller(private val {{DOMAIN_VARIABLE}}Service: {{DOMAIN_NAME}}Service) : BaseController() {

    @GetMapping
    @RequestMapping("/{{DOMAIN_BASEURL}}")
    fun getAllData(request:HttpServletRequest): List<{{DOMAIN_NAME}}> {
        return {{DOMAIN_VARIABLE}}Service.getAllData(request.parameterMap);
    }
}
    """.trimIndent().trim()


    fun generate(writeToFile: Boolean = true) {

        logger.info("Controller Code Generation - STARTING")
        val basedir = properties.basedir
        val target = properties.target
        val basePackageName = "${properties.basePackageName}.api"
        val basePackageDirectory = "$basedir/$target/${basePackageName.replace(".", "/")}"
        val tableMappings = apiBlueprints
            .map { apiDefinition -> apiDefinition.tableMapping }
            .toList()
            .flatten()

        logger.info("basedir=$basedir")
        logger.info("target=$target")
        logger.info("basePackageName=$basePackageName")
        logger.info("basePackageDirectory=$basePackageDirectory")
        logger.info("tableMappings=$tableMappings")

        tableMappings.forEach { tableMapping: ApiTableMapping ->
            val domainLowercase = tableMapping.domain.toLowerCase()
            val domainPackageName = "$basePackageName.$domainLowercase"
            val domainPackageDirectory = "$basePackageDirectory/$domainLowercase"
            createDirectories(Path.of(domainPackageDirectory))

            val output = generateTableController(tableMapping, basePackageName)

            val controller = File("$domainPackageDirectory/${tableMapping.domain}Controller.kt")
            controller.printWriter().use { out ->
                out.print("// !!!!! GENERATED BY ${this.javaClass.name} !!!!!\n")
                out.print(output)
                out.print("\n\n// !!!!! GENERATED BY ${this.javaClass.name} !!!!!\n")
            }
        }
        logger.info("Controller  Code Generation - FINISHED")
    }


    fun generateTableController(
        tableMapping: ApiTableMapping,
        basePackageName: String
    ): String {
        val domainLowercase = tableMapping.domain.toLowerCase()
        val domainPackageName = "$basePackageName.$domainLowercase"

        val model = mapOf(
            Pair("PACKAGE_NAME", domainPackageName),
            Pair("DOMAIN_NAME", tableMapping.domain),
            Pair("DOMAIN_VARIABLE", tableMapping.domain.toLowerCase()),
            Pair("DOMAIN_BASEURL", domainLowercase),
            Pair("TABLE_NAME", tableMapping.table.toUpperCase()),
            Pair("RECORD_NAME", tableMapping.record)
        )
        val handlebars = Handlebars()
        val template = handlebars.compileInline(controllerTemplate)
        return template.apply(model)
    }

}
