spring:
  main:
    web-application-type: none

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

app.datasource.main:
  initialization-mode: never
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: localhost

app.datasource.jooq:
  initialization-mode: never
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: localhost

