spring:
  main:
    web-application-type: none
  profiles:
    include:
      - blueprints
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:ddl
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: localhost

