/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempBooks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  title;
    private Integer publicationdate;

    public TempBooks() {}

    public TempBooks(TempBooks value) {
        this.id = value.id;
        this.title = value.title;
        this.publicationdate = value.publicationdate;
    }

    public TempBooks(
        Integer id,
        String  title,
        Integer publicationdate
    ) {
        this.id = id;
        this.title = title;
        this.publicationdate = publicationdate;
    }

    /**
     * Getter for <code>public.temp_books.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.temp_books.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.temp_books.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.temp_books.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.temp_books.publicationdate</code>.
     */
    public Integer getPublicationdate() {
        return this.publicationdate;
    }

    /**
     * Setter for <code>public.temp_books.publicationdate</code>.
     */
    public void setPublicationdate(Integer publicationdate) {
        this.publicationdate = publicationdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TempBooks (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(publicationdate);

        sb.append(")");
        return sb.toString();
    }
}
