blueprints-templates:
  - api/codegen-sample-blueprint.json
blueprints:
  # contains the list of blueprints for aggregation and code generation
  # base package for source code generation
  base-package: me.roybailey.codegen
  # datasource for blueprints
  datasource:
    # when enabled=true the primary dataSource is created from the below properties (only activated by services)
    enabled: false
    # these properties are used by the code generator and by derived services to access the main database
    initialization-mode: never
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: localhost
    schema: public
    excludes: .*schema.*|pg_.*
