// !!!!! GENERATED BY me.roybailey.generator.ServiceCodeGenerator !!!!!
package me.roybailey.codegen.api.books

import me.roybailey.codegen.jooq.database.Tables.BOOKS
import me.roybailey.codegen.jooq.database.tables.records.BooksRecord
import me.roybailey.codegen.jooq.database.tables.pojos.Books
import org.jooq.DSLContext
import org.springframework.stereotype.Component


@Component
class BooksService(private val dsl: DSLContext) {

    fun getAllData(): List<Books> {
        val results = dsl
            .select()
            .from(BOOKS)
            .fetch()
            .into(Books::class.java)
        return results;
    }
}
// !!!!! GENERATED BY me.roybailey.generator.ServiceCodeGenerator !!!!!
