/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempBooks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  title;
    private String  description;
    private Integer publicationdate;
    private Double  price;

    public TempBooks() {}

    public TempBooks(TempBooks value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
        this.publicationdate = value.publicationdate;
        this.price = value.price;
    }

    public TempBooks(
        Integer id,
        String  title,
        String  description,
        Integer publicationdate,
        Double  price
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.publicationdate = publicationdate;
        this.price = price;
    }

    /**
     * Getter for <code>public.temp_books.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.temp_books.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.temp_books.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.temp_books.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.temp_books.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.temp_books.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.temp_books.publicationdate</code>.
     */
    public Integer getPublicationdate() {
        return this.publicationdate;
    }

    /**
     * Setter for <code>public.temp_books.publicationdate</code>.
     */
    public void setPublicationdate(Integer publicationdate) {
        this.publicationdate = publicationdate;
    }

    /**
     * Getter for <code>public.temp_books.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.temp_books.price</code>.
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TempBooks (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(publicationdate);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
