/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTempCodegenSample implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer        id;
    private String         title;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private String         description;
    private String         periodFrom;
    private String         periodUpto;
    private Double         price;
    private Integer        discount;

    public VTempCodegenSample() {}

    public VTempCodegenSample(VTempCodegenSample value) {
        this.id = value.id;
        this.title = value.title;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.description = value.description;
        this.periodFrom = value.periodFrom;
        this.periodUpto = value.periodUpto;
        this.price = value.price;
        this.discount = value.discount;
    }

    public VTempCodegenSample(
        Integer        id,
        String         title,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        String         description,
        String         periodFrom,
        String         periodUpto,
        Double         price,
        Integer        discount
    ) {
        this.id = id;
        this.title = title;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.description = description;
        this.periodFrom = periodFrom;
        this.periodUpto = periodUpto;
        this.price = price;
        this.discount = discount;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.period_from</code>.
     */
    public String getPeriodFrom() {
        return this.periodFrom;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.period_from</code>.
     */
    public void setPeriodFrom(String periodFrom) {
        this.periodFrom = periodFrom;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.period_upto</code>.
     */
    public String getPeriodUpto() {
        return this.periodUpto;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.period_upto</code>.
     */
    public void setPeriodUpto(String periodUpto) {
        this.periodUpto = periodUpto;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.price</code>.
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.discount</code>.
     */
    public Integer getDiscount() {
        return this.discount;
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.discount</code>.
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VTempCodegenSample (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(description);
        sb.append(", ").append(periodFrom);
        sb.append(", ").append(periodUpto);
        sb.append(", ").append(price);
        sb.append(", ").append(discount);

        sb.append(")");
        return sb.toString();
    }
}
