/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import me.roybailey.codegen.jooq.database.tables.TempBooks;
import me.roybailey.codegen.jooq.database.tables.TempCities;
import me.roybailey.codegen.jooq.database.tables.records.TempBooksRecord;
import me.roybailey.codegen.jooq.database.tables.records.TempCitiesRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TempBooksRecord> TEMP_BOOKS_PKEY = Internal.createUniqueKey(TempBooks.TEMP_BOOKS, DSL.name("temp_books_pkey"), new TableField[] { TempBooks.TEMP_BOOKS.ID }, true);
    public static final UniqueKey<TempCitiesRecord> TEMP_CITIES_PKEY = Internal.createUniqueKey(TempCities.TEMP_CITIES, DSL.name("temp_cities_pkey"), new TableField[] { TempCities.TEMP_CITIES.ID }, true);
}
