/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import java.util.Arrays;
import java.util.List;

import me.roybailey.codegen.jooq.database.tables.Books;
import me.roybailey.codegen.jooq.database.tables.Cities;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.books</code>.
     */
    public final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.cities</code>.
     */
    public final Cities CITIES = Cities.CITIES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Books.BOOKS,
            Cities.CITIES
        );
    }
}
