/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import me.roybailey.codegen.jooq.database.tables.Books;
import me.roybailey.codegen.jooq.database.tables.Cities;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.cities</code>.
     */
    public static final Cities CITIES = Cities.CITIES;
}
