// !!!!! GENERATED BY me.roybailey.generator.code.ServiceCodeGenerator !!!!!
package me.roybailey.codegen.api.tempbooks

import me.roybailey.codegen.jooq.database.Tables.TEMP_BOOKS
import me.roybailey.codegen.jooq.database.tables.records.TempBooksRecord
import me.roybailey.codegen.jooq.database.tables.pojos.TempBooks
import org.jooq.*
import org.jooq.impl.DSL.*
import org.springframework.stereotype.Component


@Component
class TempBooksService(private val dsl: DSLContext) {

    fun condition(request:Map<String,Any>) {
        val result = trueCondition()
        result
    } 

    fun getAllData(): List<TempBooks> {
        val results = dsl
            .select()
            .from(TEMP_BOOKS)
            .fetch()
            .into(TempBooks::class.java)
        return results;
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ServiceCodeGenerator !!!!!
