// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
package me.roybailey.codegen.api.tempbooks

import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import me.roybailey.codegen.jooq.database.tables.pojos.TempBooks


@RestController
class TempBooksController(private val tempbooksService: TempBooksService) {

    @GetMapping
    @RequestMapping("/tempbooks")
    fun getAllData(): List<TempBooks> {
        return tempbooksService.getAllData();
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
