// !!!!! GENERATED BY me.roybailey.generator.ServiceCodeGenerator !!!!!
package me.roybailey.codegen.api.tempbooks

import me.roybailey.codegen.jooq.database.Tables.TEMP_BOOKS
import me.roybailey.codegen.jooq.database.tables.records.TempBooksRecord
import me.roybailey.codegen.jooq.database.tables.pojos.TempBooks
import org.jooq.DSLContext
import org.springframework.stereotype.Component


@Component
class TempBooksService(private val dsl: DSLContext) {

    fun getAllData(): List<TempBooks> {
        val results = dsl
            .select()
            .from(TEMP_BOOKS)
            .fetch()
            .into(TempBooks::class.java)
        return results;
    }
}
// !!!!! GENERATED BY me.roybailey.generator.ServiceCodeGenerator !!!!!
