/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables.records;


import java.time.OffsetDateTime;

import me.roybailey.codegen.jooq.database.tables.VTempCodegenSample;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VTempCodegenSampleRecord extends TableRecordImpl<VTempCodegenSampleRecord> implements Record9<Integer, String, OffsetDateTime, OffsetDateTime, String, String, String, Double, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.v_temp_codegen_sample.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.period_from</code>.
     */
    public void setPeriodFrom(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.period_from</code>.
     */
    public String getPeriodFrom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.period_upto</code>.
     */
    public void setPeriodUpto(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.period_upto</code>.
     */
    public String getPeriodUpto() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.price</code>.
     */
    public void setPrice(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.price</code>.
     */
    public Double getPrice() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.v_temp_codegen_sample.discount</code>.
     */
    public void setDiscount(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.v_temp_codegen_sample.discount</code>.
     */
    public Integer getDiscount() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, OffsetDateTime, OffsetDateTime, String, String, String, Double, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, OffsetDateTime, OffsetDateTime, String, String, String, Double, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.ID;
    }

    @Override
    public Field<String> field2() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.TITLE;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.UPDATED_AT;
    }

    @Override
    public Field<String> field5() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.PERIOD_FROM;
    }

    @Override
    public Field<String> field7() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.PERIOD_UPTO;
    }

    @Override
    public Field<Double> field8() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.PRICE;
    }

    @Override
    public Field<Integer> field9() {
        return VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE.DISCOUNT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getPeriodFrom();
    }

    @Override
    public String component7() {
        return getPeriodUpto();
    }

    @Override
    public Double component8() {
        return getPrice();
    }

    @Override
    public Integer component9() {
        return getDiscount();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getPeriodFrom();
    }

    @Override
    public String value7() {
        return getPeriodUpto();
    }

    @Override
    public Double value8() {
        return getPrice();
    }

    @Override
    public Integer value9() {
        return getDiscount();
    }

    @Override
    public VTempCodegenSampleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value6(String value) {
        setPeriodFrom(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value7(String value) {
        setPeriodUpto(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value8(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord value9(Integer value) {
        setDiscount(value);
        return this;
    }

    @Override
    public VTempCodegenSampleRecord values(Integer value1, String value2, OffsetDateTime value3, OffsetDateTime value4, String value5, String value6, String value7, Double value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VTempCodegenSampleRecord
     */
    public VTempCodegenSampleRecord() {
        super(VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE);
    }

    /**
     * Create a detached, initialised VTempCodegenSampleRecord
     */
    public VTempCodegenSampleRecord(Integer id, String title, OffsetDateTime createdAt, OffsetDateTime updatedAt, String description, String periodFrom, String periodUpto, Double price, Integer discount) {
        super(VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE);

        setId(id);
        setTitle(title);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDescription(description);
        setPeriodFrom(periodFrom);
        setPeriodUpto(periodUpto);
        setPrice(price);
        setDiscount(discount);
    }

    /**
     * Create a detached, initialised VTempCodegenSampleRecord
     */
    public VTempCodegenSampleRecord(me.roybailey.codegen.jooq.database.tables.pojos.VTempCodegenSample value) {
        super(VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setDescription(value.getDescription());
            setPeriodFrom(value.getPeriodFrom());
            setPeriodUpto(value.getPeriodUpto());
            setPrice(value.getPrice());
            setDiscount(value.getDiscount());
        }
    }
}
