/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables;


import me.roybailey.codegen.jooq.database.Keys;
import me.roybailey.codegen.jooq.database.Public;
import me.roybailey.codegen.jooq.database.tables.records.CitiesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cities extends TableImpl<CitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cities</code>
     */
    public static final Cities CITIES = new Cities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CitiesRecord> getRecordType() {
        return CitiesRecord.class;
    }

    /**
     * The column <code>public.cities.id</code>.
     */
    public final TableField<CitiesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.cities.name</code>.
     */
    public final TableField<CitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.cities.population</code>.
     */
    public final TableField<CitiesRecord, Integer> POPULATION = createField(DSL.name("population"), SQLDataType.INTEGER, this, "");

    private Cities(Name alias, Table<CitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cities(Name alias, Table<CitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.cities</code> table reference
     */
    public Cities(String alias) {
        this(DSL.name(alias), CITIES);
    }

    /**
     * Create an aliased <code>public.cities</code> table reference
     */
    public Cities(Name alias) {
        this(alias, CITIES);
    }

    /**
     * Create a <code>public.cities</code> table reference
     */
    public Cities() {
        this(DSL.name("cities"), null);
    }

    public <O extends Record> Cities(Table<O> child, ForeignKey<O, CitiesRecord> key) {
        super(child, key, CITIES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CitiesRecord, Integer> getIdentity() {
        return (Identity<CitiesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CitiesRecord> getPrimaryKey() {
        return Keys.CITIES_PKEY;
    }

    @Override
    public Cities as(String alias) {
        return new Cities(DSL.name(alias), this);
    }

    @Override
    public Cities as(Name alias) {
        return new Cities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(String name) {
        return new Cities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Name name) {
        return new Cities(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
