package me.roybailey.generator

import mu.KotlinLogging
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Component
import java.io.File
import java.nio.file.Files.createDirectories
import java.nio.file.Path


@Component
class ServiceCodeGenerator {

    private val logger = KotlinLogging.logger {}

    @Autowired
    lateinit var properties: ConfigurationProperties

    @Autowired
    lateinit var apiSpecifications: List<ApiSpecification>

    val serviceTemplate = """ 
package {{PACKAGE_NAME}}

import me.roybailey.codegen.jooq.database.Tables.{{TABLE_NAME}}
import me.roybailey.codegen.jooq.database.tables.records.{{RECORD_NAME}}
import me.roybailey.codegen.jooq.database.tables.pojos.{{DOMAIN_NAME}}
import org.jooq.DSLContext
import org.springframework.stereotype.Component


@Component
class {{DOMAIN_NAME}}Service(private val dsl: DSLContext) {

    fun getAllData(): List<{{DOMAIN_NAME}}> {
        val results = dsl
            .select()
            .from({{TABLE_NAME}})
            .fetch()
            .into({{DOMAIN_NAME}}::class.java)
        return results;
    }
}
    """.trimIndent().trim()


    fun generate() {

        logger.info("Service Code Generation - STARTING")
        val basedir = properties.basedir
        val target = properties.target
        val basePackageName = "${properties.basePackageName}.api"
        val basePackageDirectory = "$basedir/$target/${basePackageName.replace(".", "/")}"
        val tableMappings = apiSpecifications
            .map { apiDefinition -> apiDefinition.tableMapping }
            .toList()
            .flatten()

        logger.info("basedir=$basedir")
        logger.info("target=$target")
        logger.info("basePackageName=$basePackageName")
        logger.info("basePackageDirectory=$basePackageDirectory")
        logger.info("tableMappings=$tableMappings")

        File(basePackageDirectory).deleteRecursively()

        tableMappings.forEach {
            val domainLowercase = it.domain.toLowerCase()
            val domainPackageName = "$basePackageName.$domainLowercase"
            val domainPackageDirectory = "$basePackageDirectory/$domainLowercase"
            createDirectories(Path.of(domainPackageDirectory))

            val controller = File("$domainPackageDirectory/${it.domain}Service.kt")
            controller.printWriter().use { out ->
                out.print("// !!!!! GENERATED BY ${this.javaClass.name} !!!!!\n")
                out.print(
                    serviceTemplate
                        .replace("{{PACKAGE_NAME}}", domainPackageName)
                        .replace("{{DOMAIN_NAME}}", it.domain)
                        .replace("{{DOMAIN_BASEURL}}", domainLowercase)
                        .replace("{{TABLE_NAME}}", it.table)
                        .replace("{{RECORD_NAME}}", it.record)
                )
                out.print("\n\n// !!!!! GENERATED BY ${this.javaClass.name} !!!!!\n")
            }
        }
        logger.info("Service  Code Generation - FINISHED")
    }
}
