/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import java.util.Arrays;
import java.util.List;

import me.roybailey.codegen.jooq.database.tables.VTempCodegenSample;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.v_temp_codegen_sample</code>.
     */
    public final VTempCodegenSample V_TEMP_CODEGEN_SAMPLE = VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE
        );
    }
}
