/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import java.util.Arrays;
import java.util.List;

import me.roybailey.codegen.jooq.database.tables.TempBooks;
import me.roybailey.codegen.jooq.database.tables.TempCities;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.temp_books</code>.
     */
    public final TempBooks TEMP_BOOKS = TempBooks.TEMP_BOOKS;

    /**
     * The table <code>public.temp_cities</code>.
     */
    public final TempCities TEMP_CITIES = TempCities.TEMP_CITIES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TempBooks.TEMP_BOOKS,
            TempCities.TEMP_CITIES
        );
    }
}
