/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import me.roybailey.codegen.jooq.database.tables.TempBooks;
import me.roybailey.codegen.jooq.database.tables.TempCities;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.temp_books</code>.
     */
    public static final TempBooks TEMP_BOOKS = TempBooks.TEMP_BOOKS;

    /**
     * The table <code>public.temp_cities</code>.
     */
    public static final TempCities TEMP_CITIES = TempCities.TEMP_CITIES;
}
