/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database;


import me.roybailey.codegen.jooq.database.tables.VTempCodegenSample;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.v_temp_codegen_sample</code>.
     */
    public static final VTempCodegenSample V_TEMP_CODEGEN_SAMPLE = VTempCodegenSample.V_TEMP_CODEGEN_SAMPLE;
}
