// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
package me.roybailey.codegen.api.tempbooks

import javax.servlet.http.HttpServletRequest
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import me.roybailey.api.common.BaseController
import me.roybailey.codegen.jooq.database.tables.pojos.TempBooks


@RestController
class BooksLiteController(private val tempBooksService: TempBooksService) : BaseController() {

    @GetMapping
    @RequestMapping("/books-lite")
    fun getAllData(request:HttpServletRequest): List<TempBooks> {
        return tempBooksService.getAllData(request.parameterMap);
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
