// !!!!! GENERATED BY me.roybailey.generator.ControllerCodeGenerator !!!!!
package me.roybailey.codegen.api.cities

import me.roybailey.codegen.jooq.database.Tables.CITIES
import me.roybailey.codegen.jooq.database.tables.records.CitiesRecord
import me.roybailey.codegen.jooq.database.tables.pojos.Cities
import org.jooq.DSLContext
import org.jooq.impl.DSL.select
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController


@RestController
class CitiesController(private val citiesService: CitiesService) {

    @GetMapping
    @RequestMapping("/cities")
    fun getAllData(): List<Cities> {
        return citiesService.getAllData();
    }
}
// !!!!! GENERATED BY me.roybailey.generator.ControllerCodeGenerator !!!!!
