// !!!!! GENERATED BY ModelCodeGenerator !!!!!
package me.roybailey.codegen.api.codegensample

import com.fasterxml.jackson.annotation.JsonProperty
import java.sql.Timestamp


data class CodegenSampleModel (
    
    @JsonProperty("id") var id: Integer,
    
    @JsonProperty("title") var title: String,
    
    @JsonProperty("created_at") var created_at: Timestamp,
    
    @JsonProperty("updated_at") var updated_at: Timestamp,
    
    @JsonProperty("description") var description: String,
    
    @JsonProperty("periodfrom") var periodfrom: String,
    
    @JsonProperty("periodupto") var periodupto: String,
    
    @JsonProperty("price") var price: Double,
    
    @JsonProperty("discount") var discount: Double,
    
)

// !!!!! GENERATED BY ModelCodeGenerator !!!!!
