// !!!!! GENERATED BY ModelCodeGenerator !!!!!
package me.roybailey.codegen.api.codegensample

import com.fasterxml.jackson.annotation.JsonProperty
import java.sql.Timestamp


data class CodegenSampleModel (
    
    @JsonProperty("id") var id: Integer,
    
    @JsonProperty("title") var title: String,
    
    @JsonProperty("createdAt") var created_at: Timestamp,
    
    @JsonProperty("updatedAt") var updated_at: Timestamp,
    
    @JsonProperty("description") var description: String,
    
    @JsonProperty("periodFrom") var period_from: String,
    
    @JsonProperty("periodUpto") var period_upto: String,
    
    @JsonProperty("price") var price: Double,
    
    @JsonProperty("discount") var discount: Integer,
    
)

// !!!!! GENERATED BY ModelCodeGenerator !!!!!
