// !!!!! GENERATED BY ServiceCodeGenerator !!!!!
package me.roybailey.codegen.api.codegensample

import me.roybailey.api.common.BaseService
import me.roybailey.codegen.jooq.database.Tables.V_TEMP_CODEGEN_SAMPLE
import me.roybailey.codegen.api.codegensample.CodegenSampleModel

import org.jooq.*
import org.jooq.impl.DSL.*
import org.springframework.stereotype.Component


@Component
class CodegenSampleService(
    protected open val dsl: DSLContext
) : BaseService(
    blueprintId = "codegen-sample-blueprint",
    serviceMappingId = "codegen-sample-service",
    tableMappingId = "codegen-sample-table",
    modelMappingId = "codegen-sample-model"
) {

    fun getAllData(params: Map<String,Any>): List<CodegenSampleModel> {
        val results = dsl
            .select()
            .from(V_TEMP_CODEGEN_SAMPLE)
            .where(getFilterCondition(params, V_TEMP_CODEGEN_SAMPLE))
            .limit(100)
            .fetch()
            .into(CodegenSampleModel::class.java)
        return results;
    }
}

// !!!!! GENERATED BY ServiceCodeGenerator !!!!!
