// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
package me.roybailey.codegen.api.tempcities

import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import me.roybailey.codegen.jooq.database.tables.pojos.TempCities


@RestController
class TempCitiesController(private val tempcitiesService: TempCitiesService) {

    @GetMapping
    @RequestMapping("/tempcities")
    fun getAllData(): List<TempCities> {
        return tempcitiesService.getAllData();
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ControllerCodeGenerator !!!!!
