/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables.records;


import me.roybailey.codegen.jooq.database.tables.TempBooks;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempBooksRecord extends UpdatableRecordImpl<TempBooksRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.temp_books.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.temp_books.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.temp_books.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.temp_books.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.temp_books.publicationdate</code>.
     */
    public void setPublicationdate(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.temp_books.publicationdate</code>.
     */
    public Integer getPublicationdate() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TempBooks.TEMP_BOOKS.ID;
    }

    @Override
    public Field<String> field2() {
        return TempBooks.TEMP_BOOKS.TITLE;
    }

    @Override
    public Field<Integer> field3() {
        return TempBooks.TEMP_BOOKS.PUBLICATIONDATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public Integer component3() {
        return getPublicationdate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public Integer value3() {
        return getPublicationdate();
    }

    @Override
    public TempBooksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TempBooksRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TempBooksRecord value3(Integer value) {
        setPublicationdate(value);
        return this;
    }

    @Override
    public TempBooksRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TempBooksRecord
     */
    public TempBooksRecord() {
        super(TempBooks.TEMP_BOOKS);
    }

    /**
     * Create a detached, initialised TempBooksRecord
     */
    public TempBooksRecord(Integer id, String title, Integer publicationdate) {
        super(TempBooks.TEMP_BOOKS);

        setId(id);
        setTitle(title);
        setPublicationdate(publicationdate);
    }

    /**
     * Create a detached, initialised TempBooksRecord
     */
    public TempBooksRecord(me.roybailey.codegen.jooq.database.tables.pojos.TempBooks value) {
        super(TempBooks.TEMP_BOOKS);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setPublicationdate(value.getPublicationdate());
        }
    }
}
