/*
 * This file is generated by jOOQ.
 */
package me.roybailey.codegen.jooq.database.tables.records;


import me.roybailey.codegen.jooq.database.tables.TempCities;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempCitiesRecord extends UpdatableRecordImpl<TempCitiesRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.temp_cities.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.temp_cities.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.temp_cities.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.temp_cities.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.temp_cities.population</code>.
     */
    public void setPopulation(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.temp_cities.population</code>.
     */
    public Integer getPopulation() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TempCities.TEMP_CITIES.ID;
    }

    @Override
    public Field<String> field2() {
        return TempCities.TEMP_CITIES.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return TempCities.TEMP_CITIES.POPULATION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getPopulation();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getPopulation();
    }

    @Override
    public TempCitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TempCitiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TempCitiesRecord value3(Integer value) {
        setPopulation(value);
        return this;
    }

    @Override
    public TempCitiesRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TempCitiesRecord
     */
    public TempCitiesRecord() {
        super(TempCities.TEMP_CITIES);
    }

    /**
     * Create a detached, initialised TempCitiesRecord
     */
    public TempCitiesRecord(Integer id, String name, Integer population) {
        super(TempCities.TEMP_CITIES);

        setId(id);
        setName(name);
        setPopulation(population);
    }

    /**
     * Create a detached, initialised TempCitiesRecord
     */
    public TempCitiesRecord(me.roybailey.codegen.jooq.database.tables.pojos.TempCities value) {
        super(TempCities.TEMP_CITIES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setPopulation(value.getPopulation());
        }
    }
}
