// !!!!! GENERATED BY me.roybailey.generator.code.PojoCodeGenerator !!!!!
package me.roybailey.codegen.api.tempbooks

import com.fasterxml.jackson.annotation.JsonProperty


data class TempBooks (
    
    @JsonProperty("publicationdate") var publicationdate: Integer,
    
    @JsonProperty("price") var price: Double,
    
    @JsonProperty("id") var id: Integer,
    
    @JsonProperty("title") var title: String,
    
    @JsonProperty("description") var description: String,
    
)

// !!!!! GENERATED BY me.roybailey.generator.code.PojoCodeGenerator !!!!!
