// !!!!! GENERATED BY me.roybailey.generator.code.ServiceCodeGenerator !!!!!
package me.roybailey.codegen.api.tempbooks

import me.roybailey.api.common.BaseService
import me.roybailey.codegen.jooq.database.Tables.TEMP_BOOKS
import me.roybailey.codegen.jooq.database.tables.records.TempBooksRecord
import me.roybailey.codegen.jooq.database.tables.pojos.TempBooks
import org.jooq.*
import org.jooq.impl.DSL.*
import org.springframework.stereotype.Component


@Component
class TempBooksService(protected open val dsl: DSLContext) : BaseService("books","temp_books") {

    fun getAllData(params: Map<String,Any>): List<TempBooks> {
        val results = dsl
            .select()
            .from(TEMP_BOOKS)
            .where(getFilterCondition(params, TEMP_BOOKS))
            .fetch()
            .into(TempBooks::class.java)
        return results;
    }
}

// !!!!! GENERATED BY me.roybailey.generator.code.ServiceCodeGenerator !!!!!
